### PR TITLE
Patch 1.5.3 (Translation)

### PR DESCRIPTION
**Pull request by AntonnMal**
- Added an easy way to translate
- Added russian translation
- Removed now unused functions
- Removed useless build targets
- Put block bot under "Unfinished" in misc

### CODE REVIEW

**Comment by martinjanas** [comment]
Thank you for your work, but I think you wasted your time with the translation stuff, because most ppl can understand english.

**Comment by AntonnMal** [comment]
Maybe i wasted my time, but i had fun

**Comment by martinjanas** [comment]
> Maybe i wasted my time, but i had fun

I will consider it. Probably gonna rewrite it a little bit to make it compact as possible.

**Comment by AntonnMal** [comment]
Ok, sure

**Comment by AntonnMal** [comment]
Quick question: would a report bot be welcomed?

**Comment by martinjanas** [comment]
Report bots dont work.

**Comment by AntonnMal** [comment]
Thanks for the info

**Pull request closed without merging**
